import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    dashboard: "Dashboard",
    graph: "Name Graph",
    favorites: "Favorites",
    about: "About", // <--- NEW
    search: "Search names...",
    searchBar: "Search...",
    filter_gender: "Gender",
    gender: "Gender",
    filter_origin: "Origin",
    filter_quranic: "Quranic Only",
    rank: "Rank",
    count: "Total Count",
    male: "Male",
    female: "Female",
    unisex: "Unisex",
    details: "Details",
    usage_chart: "Usage Over Time",
    distribution: "Distribution Map",
    meaning: "Meaning",
    origin: "Origin",
    similar_names: "Similar Names",
    back: "Back to List",
    quranic: "Quranic?",
    all: "All",
    turkish: "Turkish",
    arabic: "Arabic",
    farsi: "Farsi",
    greek: "Greek",
    english: "English",
    western: "Western",
    results: "results",
    isQuranic: "Quranic",
    graphLegend: "Grouped by semantic meaning",
    show: "Show Names",
    showNum: "Show",
    showAll: "Show all",
    hide: "Hide Names",
    names: "Names",
    name: "Name",
    resetView: "Reset View",
    page: "Page",
    namesFound: "names found", 
    total: "Total",
    nodeSize: "Node Size",
    color: "Color",
    noFavorites: "No favorites yet",
    addFavorites: "Start exploring to add names!",
    rankMode: "Reorder List",
    rankHelp: "Use arrows to rank your top names",
    filterFavorites: "Filter Favorites",
    noLikedNames: "No liked names found.",
    noCriteria: "No names matching your criteria.",
    // --- POPUP TRANSLATIONS ---
    graphHelpTitle: "About the Graph",
    graphHelpDesc: "This interactive network visualizes names based on semantic similarity. Names with similar meanings appear closer together.",
    graphHelpNav: "Navigation",
    graphHelpNavDesc: "Click and drag to pan. Scroll to zoom in and out.",
    graphHelpZoom: "View Controls",
    graphHelpZoomDesc: "Use the controls in the sidebar to filter data or change colors.",
    graphHelpClick: "Interaction",
    graphHelpClickDesc: "Click a node to focus. Hover to see detailed information.",
    gotIt: "Got it, thanks!",
    random: "Find a random name!",
    randomName: "Random name!",
    // --- ABOUT PAGE ---
    aboutTitle: "About İsimBul",
    aboutDesc: "İsimBul is an interactive platform designed to explore the etymology, statistical usage, and semantic relationships of Turkish names.",
    dataSources: "Data Sources & Credits",
    nisanyanCredit: "The etymological data, name definitions, and historical context used in this project are sourced from the invaluable work of Sevan Nişanyan.",
    visitNisanyan: "Visit Nişanyan Adlar",
    disclaimer: "Disclaimer",
    disclaimerText: "This is an educational project. While we strive for accuracy, please refer to the original sources for academic citations.",
    contact: "Contact",
  },
  tr: {
    dashboard: "Panel",
    graph: "İsim Grafiği",
    favorites: "Favoriler",
    about: "Hakkında", // <--- NEW
    search: "İsim ara...",
    searchBar: "Ara...",
    filter_gender: "Cinsiyet",
    gender: "Cinsiyet",
    filter_origin: "Köken",
    filter_quranic: "Sadece Kuran'da Geçen",
    rank: "Sıralama",
    count: "Toplam Kullanım",
    male: "Erkek",
    female: "Kadın",
    unisex: "Üniseks",
    details: "Detaylar",
    usage_chart: "Zamanla Kullanım",
    distribution: "Dağılım Haritası",
    meaning: "Anlam",
    origin: "Köken",
    similar_names: "Benzer İsimler",
    back: "Listeye Dön",
    quranic: "Kuran'da Geçer mi?",
    all: "Tümü",
    turkish: "Türkçe",
    arabic: "Arapça",
    farsi: "Farsça",
    western: "Batılı",
    greek: "Yunanca",
    english: "İngilizce",
    results: "sonuç",
    isQuranic: "Kuran'da Geçer",
    graphLegend: "İsimler anlamlarına göre kümelenmiş",
    show: "İsimleri Göster",
    showNum: "Tane Göster",
    showAll: "Tümünü Göster",
    hide: "İsimleri Gösterme",
    names: "İsimleri",
    name: "İsim",
    resetView: "Görüntüyü Sıfırla",
    page: "Sayfa",
    namesFound: "adet isim bulundu",
    total: "Toplam",
    nodeSize: "Nokta Büyüklüğü",
    color: "Renk",
    noFavorites: "Henüz favori yok",
    addFavorites: "İsim eklemek için keşfetmeye başlayın!",
    rankMode: "Sıralamayı Düzenle",
    rankHelp: "Okları kullanarak favorilerini sırala",
    filterFavorites: "Favorileri Filtrele",
    noLikedNames: "Beğenilen isim bulunamadı.",
    noCriteria: "Kriterlere göre isim bulunamadı.",
    // --- POPUP TRANSLATIONS ---
    graphHelpTitle: "Grafik Hakkında",
    graphHelpDesc: "Bu etkileşimli ağ, isimleri anlamsal benzerliklerine göre görselleştirir. Benzer anlama sahip isimler birbirine daha yakın görünür.",
    graphHelpNav: "Navigasyon",
    graphHelpNavDesc: "Kaydırmak için sürükleyin. Yakınlaşmak/uzaklaşmak için fare tekerleğini kullanın.",
    graphHelpZoom: "Görünüm Kontrolleri",
    graphHelpZoomDesc: "Verileri filtrelemek veya renkleri değiştirmek için kenar çubuğunu kullanın.",
    graphHelpClick: "Etkileşim",
    graphHelpClickDesc: "Odaklanmak için isme tıklayın. Detaylar için üzerine gelin.",
    gotIt: "Anladım, teşekkürler!",
    random: "Rastgele bir isim bul!",
    randomName: "Rastgele isim!",
    // --- ABOUT PAGE ---
    aboutTitle: "İsimBul Hakkında",
    aboutDesc: "İsimBul, Türkçe isimlerin kökenbilimini, kullanım istatistiklerini ve anlamsal ilişkilerini keşfetmek için tasarlanmış etkileşimli bir platformdur.",
    dataSources: "Veri Kaynakları ve Teşekkür",
    nisanyanCredit: "Bu projede kullanılan etimolojik veriler, isim tanımları ve tarihsel bağlam, Sevan Nişanyan'ın paha biçilemez çalışmalarından derlenmiştir.",
    visitNisanyan: "Nişanyan Adlar'ı Ziyaret Et",
    disclaimer: "Yasal Uyarı",
    disclaimerText: "Bu bir eğitim projesidir. Doğruluk için çaba gösterilse de, akademik alıntılar için lütfen orijinal kaynaklara başvurunuz.",
    contact: "İletişim",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('tr');
  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);