export const SCRIPTS = [
  {
    id: 'greek',
    title: 'Greek Alphabet',
    description: 'The classical script of philosophy and mathematics.',
    color: 'bg-blue-700',
    items: [
      { char: 'Α α', name: 'Alpha', accepted: ['alpha', 'a'] },
      { char: 'Β β', name: 'Beta', accepted: ['beta', 'b'] },
      { char: 'Γ γ', name: 'Gamma', accepted: ['gamma', 'g'] },
      { char: 'Δ δ', name: 'Delta', accepted: ['delta', 'd'] },
      { char: 'Ε ε', name: 'Epsilon', accepted: ['epsilon', 'e'] },
      { char: 'Ζ ζ', name: 'Zeta', accepted: ['zeta', 'z'] },
      { char: 'Η η', name: 'Eta', accepted: ['eta', 'h', 'ē'] },
      { char: 'Θ θ', name: 'Theta', accepted: ['theta', 'th'] },
      { char: 'Ι ι', name: 'Iota', accepted: ['iota', 'i'] },
      { char: 'Κ κ', name: 'Kappa', accepted: ['kappa', 'k'] },
      { char: 'Λ λ', name: 'Lambda', accepted: ['lambda', 'l'] },
      { char: 'Μ μ', name: 'Mu', accepted: ['mu', 'm'] },
      { char: 'Ν ν', name: 'Nu', accepted: ['nu', 'n'] },
      { char: 'Ξ ξ', name: 'Xi', accepted: ['xi', 'x'] },
      { char: 'Ο ο', name: 'Omicron', accepted: ['omicron', 'o'] },
      { char: 'Π π', name: 'Pi', accepted: ['pi', 'p'] },
      { char: 'Ρ ρ', name: 'Rho', accepted: ['rho', 'r'] },
      { char: 'Σ σ/ς', name: 'Sigma', accepted: ['sigma', 's'] },
      { char: 'Τ τ', name: 'Tau', accepted: ['tau', 't'] },
      { char: 'Υ υ', name: 'Upsilon', accepted: ['upsilon', 'y', 'u'] },
      { char: 'Φ φ', name: 'Phi', accepted: ['phi', 'ph', 'f'] },
      { char: 'Χ χ', name: 'Chi', accepted: ['chi', 'ch'] },
      { char: 'Ψ ψ', name: 'Psi', accepted: ['psi', 'ps'] },
      { char: 'Ω ω', name: 'Omega', accepted: ['omega', 'w', 'ō'] },
    ]
  },
  {
    id: 'cyrillic',
    title: 'Russian Cyrillic',
    description: 'The standard script of the Russian language.',
    color: 'bg-red-700',
    items: [
      { char: 'А а', name: 'A', accepted: ['a'] },
      { char: 'Б б', name: 'Be', accepted: ['be', 'b'] },
      { char: 'В в', name: 'Ve', accepted: ['ve', 'v'] },
      { char: 'Г г', name: 'Ge', accepted: ['ge', 'g'] },
      { char: 'Д д', name: 'De', accepted: ['de', 'd'] },
      { char: 'Е е', name: 'Ye', accepted: ['ye', 'je', 'ie', 'e'] },
      { char: 'Ё ё', name: 'Yo', accepted: ['yo', 'jo'] },
      { char: 'Ж ж', name: 'Zhe', accepted: ['zhe', 'zh'] },
      { char: 'З з', name: 'Ze', accepted: ['ze', 'z'] },
      { char: 'И и', name: 'I', accepted: ['i', 'ee'] },
      { char: 'Й й', name: 'Short I', accepted: ['short i', 'y', 'j', 'ikratkoye'] },
      { char: 'К к', name: 'Ka', accepted: ['ka', 'k'] },
      { char: 'Л л', name: 'El', accepted: ['el', 'l'] },
      { char: 'М м', name: 'Em', accepted: ['em', 'm'] },
      { char: 'Н н', name: 'En', accepted: ['en', 'n'] },
      { char: 'О о', name: 'O', accepted: ['o'] },
      { char: 'П п', name: 'Pe', accepted: ['pe', 'p'] },
      { char: 'Р р', name: 'Er', accepted: ['er', 'r'] },
      { char: 'С с', name: 'Es', accepted: ['es', 's'] },
      { char: 'Т т', name: 'Te', accepted: ['te', 't'] },
      { char: 'У у', name: 'U', accepted: ['u', 'oo'] },
      { char: 'Ф ф', name: 'Ef', accepted: ['ef', 'f'] },
      { char: 'Х х', name: 'Kha', accepted: ['kha', 'h', 'kh'] },
      { char: 'Ц ц', name: 'Tse', accepted: ['tse', 'ts', 'c'] },
      { char: 'Ч ч', name: 'Che', accepted: ['che', 'ch'] },
      { char: 'Ш ш', name: 'Sha', accepted: ['sha', 'sh'] },
      { char: 'Щ щ', name: 'Shcha', accepted: ['shcha', 'shch', 'sch'] },
      { char: 'Ъ ъ', name: 'Hard Sign', accepted: ['hard sign', 'tverdy znak'] },
      { char: 'Ы ы', name: 'Yery', accepted: ['yery', 'y', 'i'] },
      { char: 'Ь ь', name: 'Soft Sign', accepted: ['soft sign', 'myagky znak'] },
      { char: 'Э э', name: 'E', accepted: ['e', 'eh'] },
      { char: 'Ю ю', name: 'Yu', accepted: ['yu', 'ju'] },
      { char: 'Я я', name: 'Ya', accepted: ['ya', 'ja'] },
    ]
  },
  {
    id: 'georgian',
    title: 'Georgian (Mkhedruli)',
    description: 'The elegant, unicase script used for Georgian.',
    color: 'bg-rose-700',
    items: [
      { char: 'ა', name: 'An', accepted: ['an', 'a'] },
      { char: 'ბ', name: 'Ban', accepted: ['ban', 'b'] },
      { char: 'გ', name: 'Gan', accepted: ['gan', 'g'] },
      { char: 'დ', name: 'Don', accepted: ['don', 'd'] },
      { char: 'ე', name: 'En', accepted: ['en', 'e'] },
      { char: 'ვ', name: 'Vin', accepted: ['vin', 'v'] },
      { char: 'ზ', name: 'Zen', accepted: ['zen', 'z'] },
      { char: 'თ', name: 'Tan', accepted: ['tan', 't'] },
      { char: 'ი', name: 'In', accepted: ['in', 'i'] },
      { char: 'კ', name: 'K\'an', accepted: ['kan', 'k'] },
      { char: 'ლ', name: 'Las', accepted: ['las', 'l'] },
      { char: 'მ', name: 'Man', accepted: ['man', 'm'] },
      { char: 'ნ', name: 'Nar', accepted: ['nar', 'n'] },
      { char: 'ო', name: 'On', accepted: ['on', 'o'] },
      { char: 'პ', name: 'P\'ar', accepted: ['par', 'p'] },
      { char: 'ჟ', name: 'Zhan', accepted: ['zhan', 'zh'] },
      { char: 'რ', name: 'Rae', accepted: ['rae', 'r'] },
      { char: 'ს', name: 'San', accepted: ['san', 's'] },
      { char: 'ტ', name: 'T\'ar', accepted: ['tar', 't'] },
      { char: 'უ', name: 'Un', accepted: ['un', 'u'] },
      { char: 'ფ', name: 'Par', accepted: ['par', 'p'] },
      { char: 'ქ', name: 'Kan', accepted: ['kan', 'k'] },
      { char: 'ღ', name: 'Ghan', accepted: ['ghan', 'gh'] },
      { char: 'ყ', name: 'Q\'ar', accepted: ['qar', 'q'] },
      { char: 'შ', name: 'Shin', accepted: ['shin', 'sh'] },
      { char: 'ჩ', name: 'Chin', accepted: ['chin', 'ch'] },
      { char: 'ც', name: 'Ts\'an', accepted: ['tsan', 'c', 'ts'] },
      { char: 'ძ', name: 'Dzil', accepted: ['dzil', 'dz'] },
      { char: 'წ', name: 'Ts\'il', accepted: ['tsil', 'ts'] },
      { char: 'ჭ', name: 'Ch\'ar', accepted: ['char', 'ch'] },
      { char: 'ხ', name: 'Khan', accepted: ['khan', 'kh', 'x'] },
      { char: 'ჯ', name: 'Jhan', accepted: ['jhan', 'j', 'dj'] },
      { char: 'ჰ', name: 'Hae', accepted: ['hae', 'h'] },
    ]
  },
  {
    id: 'arabic',
    title: 'Arabic',
    description: 'The primary script of the Islamic world.',
    color: 'bg-emerald-600',
    items: [
      { char: 'ا', name: 'Alif', accepted: ['alif', 'a'] },
      { char: 'ب', name: 'Ba', accepted: ['ba', 'b'] },
      { char: 'ت', name: 'Ta', accepted: ['ta', 't'] },
      { char: 'ث', name: 'Tha', accepted: ['tha', 'th'] },
      { char: 'ج', name: 'Jim', accepted: ['jim', 'j', 'jeem'] },
      { char: 'ح', name: 'Ha', accepted: ['ha', 'h'] },
      { char: 'خ', name: 'Kha', accepted: ['kha', 'kh'] },
      { char: 'د', name: 'Dal', accepted: ['dal', 'd'] },
      { char: 'ذ', name: 'Dhal', accepted: ['dhal', 'dh', 'zal'] },
      { char: 'ر', name: 'Ra', accepted: ['ra', 'r'] },
      { char: 'ز', name: 'Zay', accepted: ['zay', 'z', 'zayn'] },
      { char: 'س', name: 'Sin', accepted: ['sin', 's'] },
      { char: 'ش', name: 'Shin', accepted: ['shin', 'sh'] },
      { char: 'ص', name: 'Sad', accepted: ['sad', 's'] },
      { char: 'ض', name: 'Dad', accepted: ['dad', 'd', 'dhad'] },
      { char: 'ط', name: 'Ta', accepted: ['ta', 't'] },
      { char: 'ظ', name: 'Za', accepted: ['za', 'z'] },
      { char: 'ع', name: 'Ayn', accepted: ['ayn', 'ain'] },
      { char: 'غ', name: 'Ghayn', accepted: ['ghayn', 'gh'] },
      { char: 'ف', name: 'Fa', accepted: ['fa', 'f'] },
      { char: 'ق', name: 'Qaf', accepted: ['qaf', 'q'] },
      { char: 'ك', name: 'Kaf', accepted: ['kaf', 'k'] },
      { char: 'ل', name: 'Lam', accepted: ['lam', 'l'] },
      { char: 'م', name: 'Mim', accepted: ['mim', 'm'] },
      { char: 'ن', name: 'Nun', accepted: ['nun', 'n'] },
      { char: 'ه', name: 'Ha', accepted: ['ha', 'h'] },
      { char: 'و', name: 'Waw', accepted: ['waw', 'w', 'u'] },
      { char: 'ي', name: 'Ya', accepted: ['ya', 'y', 'i'] },
    ]
  },
  {
    id: 'thai',
    title: 'Thai Consonants',
    description: 'The major consonants of the Thai alphabet.',
    color: 'bg-violet-600',
    items: [
      { char: 'ก', name: 'Ko Kai', accepted: ['ko kai', 'k', 'g'] },
      { char: 'ข', name: 'Kho Khai', accepted: ['kho khai', 'kh', 'k'] },
      { char: 'ค', name: 'Kho Khwai', accepted: ['kho khwai', 'kh', 'k'] },
      { char: 'ง', name: 'Ngo Ngu', accepted: ['ngo ngu', 'ng'] },
      { char: 'จ', name: 'Cho Chan', accepted: ['cho chan', 'ch', 'j'] },
      { char: 'ฉ', name: 'Cho Ching', accepted: ['cho ching', 'ch'] },
      { char: 'ช', name: 'Cho Chang', accepted: ['cho chang', 'ch'] },
      { char: 'ซ', name: 'So So', accepted: ['so so', 's'] },
      { char: 'ญ', name: 'Yo Ying', accepted: ['yo ying', 'y'] },
      { char: 'ด', name: 'Do Dek', accepted: ['do dek', 'd'] },
      { char: 'ต', name: 'To Tao', accepted: ['to tao', 't'] },
      { char: 'ถ', name: 'Tho Thung', accepted: ['tho thung', 'th'] },
      { char: 'ท', name: 'Tho Thahan', accepted: ['tho thahan', 'th', 't'] },
      { char: 'ธ', name: 'Tho Thong', accepted: ['tho thong', 'th', 't'] },
      { char: 'น', name: 'No Nu', accepted: ['no nu', 'n'] },
      { char: 'บ', name: 'Bo Baimai', accepted: ['bo baimai', 'b'] },
      { char: 'ป', name: 'Po Pla', accepted: ['po pla', 'p'] },
      { char: 'ผ', name: 'Pho Phueng', accepted: ['pho phueng', 'ph'] },
      { char: 'ฝ', name: 'Fo Fa', accepted: ['fo fa', 'f'] },
      { char: 'พ', name: 'Pho Phan', accepted: ['pho phan', 'ph', 'p'] },
      { char: 'ฟ', name: 'Fo Fan', accepted: ['fo fan', 'f'] },
      { char: 'ม', name: 'Mo Ma', accepted: ['mo ma', 'm'] },
      { char: 'ย', name: 'Yo Yak', accepted: ['yo yak', 'y'] },
      { char: 'ร', name: 'Ro Ruea', accepted: ['ro ruea', 'r'] },
      { char: 'ล', name: 'Lo Ling', accepted: ['lo ling', 'l'] },
      { char: 'ว', name: 'Wo Waen', accepted: ['wo waen', 'w'] },
      { char: 'ส', name: 'So Suea', accepted: ['so suea', 's'] },
      { char: 'ห', name: 'Ho Hip', accepted: ['ho hip', 'h'] },
      { char: 'อ', name: 'O Ang', accepted: ['o ang', 'o'] },
      { char: 'ฮ', name: 'Ho Nokhuk', accepted: ['ho nokhuk', 'h'] },
    ]
  },
  {
    id: 'farsi',
    title: 'Farsi (Persian)',
    description: 'Derived from Arabic, with four additional letters.',
    color: 'bg-teal-600',
    items: [
      { char: 'ا', name: 'Alef', accepted: ['alef', 'a'] },
      { char: 'ب', name: 'Be', accepted: ['be', 'b'] },
      { char: 'پ', name: 'Pe', accepted: ['pe', 'p'] },
      { char: 'ت', name: 'Te', accepted: ['te', 't'] },
      { char: 'ث', name: 'Se', accepted: ['se', 's'] },
      { char: 'ج', name: 'Jim', accepted: ['jim', 'j'] },
      { char: 'چ', name: 'Che', accepted: ['che', 'ch'] },
      { char: 'ح', name: 'He', accepted: ['he', 'h'] },
      { char: 'خ', name: 'Khe', accepted: ['khe', 'kh'] },
      { char: 'د', name: 'Dal', accepted: ['dal', 'd'] },
      { char: 'ذ', name: 'Zal', accepted: ['zal', 'z'] },
      { char: 'ر', name: 'Re', accepted: ['re', 'r'] },
      { char: 'ز', name: 'Ze', accepted: ['ze', 'z'] },
      { char: 'ژ', name: 'Zhe', accepted: ['zhe', 'zh'] },
      { char: 'س', name: 'Sin', accepted: ['sin', 's'] },
      { char: 'ش', name: 'Shin', accepted: ['shin', 'sh'] },
      { char: 'ص', name: 'Sad', accepted: ['sad', 's'] },
      { char: 'ض', name: 'Zad', accepted: ['zad', 'z'] },
      { char: 'ط', name: 'Ta', accepted: ['ta', 't'] },
      { char: 'ظ', name: 'Za', accepted: ['za', 'z'] },
      { char: 'ع', name: 'Ayn', accepted: ['ayn'] },
      { char: 'غ', name: 'Ghayn', accepted: ['ghayn', 'gh'] },
      { char: 'ف', name: 'Fe', accepted: ['fe', 'f'] },
      { char: 'ق', name: 'Qaf', accepted: ['qaf', 'q', 'ghaf'] },
      { char: 'ک', name: 'Kaf', accepted: ['kaf', 'k'] },
      { char: 'گ', name: 'Gaf', accepted: ['gaf', 'g'] },
      { char: 'ل', name: 'Lam', accepted: ['lam', 'l'] },
      { char: 'م', name: 'Mim', accepted: ['mim', 'm'] },
      { char: 'ن', name: 'Nun', accepted: ['nun', 'n'] },
      { char: 'و', name: 'Vav', accepted: ['vav', 'v'] },
      { char: 'ه', name: 'He', accepted: ['he', 'h'] },
      { char: 'ی', name: 'Ye', accepted: ['ye', 'y', 'i'] },
    ]
  },
  {
    id: 'hindi',
    title: 'Hindi (Devanagari)',
    description: 'The primary script for Hindi, Sanskrit, and Marathi.',
    color: 'bg-orange-600',
    items: [
      { char: 'अ', name: 'A', accepted: ['a'] },
      { char: 'आ', name: 'Aa', accepted: ['aa'] },
      { char: 'इ', name: 'I', accepted: ['i'] },
      { char: 'ई', name: 'Ii', accepted: ['ii', 'ee'] },
      { char: 'उ', name: 'U', accepted: ['u'] },
      { char: 'ऊ', name: 'Uu', accepted: ['uu', 'oo'] },
      { char: 'ए', name: 'E', accepted: ['e'] },
      { char: 'ऐ', name: 'Ai', accepted: ['ai'] },
      { char: 'ओ', name: 'O', accepted: ['o'] },
      { char: 'औ', name: 'Au', accepted: ['au'] },
      { char: 'क', name: 'Ka', accepted: ['ka', 'k'] },
      { char: 'ख', name: 'Kha', accepted: ['kha', 'kh'] },
      { char: 'ग', name: 'Ga', accepted: ['ga', 'g'] },
      { char: 'घ', name: 'Gha', accepted: ['gha', 'gh'] },
      { char: 'च', name: 'Cha', accepted: ['cha', 'ch'] },
      { char: 'छ', name: 'Chha', accepted: ['chha', 'chh'] },
      { char: 'ज', name: 'Ja', accepted: ['ja', 'j'] },
      { char: 'झ', name: 'Jha', accepted: ['jha', 'jh'] },
      { char: 'ट', name: 'Ta', accepted: ['ta', 't'] },
      { char: 'ठ', name: 'Tha', accepted: ['tha', 'th'] },
      { char: 'ड', name: 'Da', accepted: ['da', 'd'] },
      { char: 'ढ', name: 'Dha', accepted: ['dha', 'dh'] },
      { char: 'ण', name: 'Na', accepted: ['na', 'n'] },
      { char: 'त', name: 'Ta', accepted: ['ta', 't'] },
      { char: 'थ', name: 'Tha', accepted: ['tha', 'th'] },
      { char: 'द', name: 'Da', accepted: ['da', 'd'] },
      { char: 'ध', name: 'Dha', accepted: ['dha', 'dh'] },
      { char: 'न', name: 'Na', accepted: ['na', 'n'] },
      { char: 'प', name: 'Pa', accepted: ['pa', 'p'] },
      { char: 'फ', name: 'Pha', accepted: ['pha', 'ph', 'fa'] },
      { char: 'ब', name: 'Ba', accepted: ['ba', 'b'] },
      { char: 'भ', name: 'Bha', accepted: ['bha', 'bh'] },
      { char: 'म', name: 'Ma', accepted: ['ma', 'm'] },
      { char: 'य', name: 'Ya', accepted: ['ya', 'y'] },
      { char: 'र', name: 'Ra', accepted: ['ra', 'r'] },
      { char: 'ल', name: 'La', accepted: ['la', 'l'] },
      { char: 'व', name: 'Va', accepted: ['va', 'v', 'wa'] },
      { char: 'श', name: 'Sha', accepted: ['sha', 'sh'] },
      { char: 'ष', name: 'Sha', accepted: ['sha', 'sh'] },
      { char: 'स', name: 'Sa', accepted: ['sa', 's'] },
      { char: 'ह', name: 'Ha', accepted: ['ha', 'h'] },
    ]
  },
  {
    id: 'odia',
    title: 'Odia',
    description: 'The distinctive rounded script of Odisha.',
    color: 'bg-fuchsia-700',
    items: [
      { char: 'ଅ', name: 'A', accepted: ['a'] },
      { char: 'ଆ', name: 'Aa', accepted: ['aa'] },
      { char: 'ଇ', name: 'I', accepted: ['i'] },
      { char: 'ଈ', name: 'Ii', accepted: ['ii', 'ee'] },
      { char: 'ଉ', name: 'U', accepted: ['u'] },
      { char: 'ଊ', name: 'Uu', accepted: ['uu', 'oo'] },
      { char: 'ଋ', name: 'Ru', accepted: ['ru', 'r'] },
      { char: 'ଏ', name: 'E', accepted: ['e'] },
      { char: 'ଐ', name: 'Ai', accepted: ['ai'] },
      { char: 'ଓ', name: 'O', accepted: ['o'] },
      { char: 'ଔ', name: 'Au', accepted: ['au', 'ou'] },
      { char: 'କ', name: 'Ka', accepted: ['ka', 'k'] },
      { char: 'ଖ', name: 'Kha', accepted: ['kha', 'kh'] },
      { char: 'ଗ', name: 'Ga', accepted: ['ga', 'g'] },
      { char: 'ଘ', name: 'Gha', accepted: ['gha', 'gh'] },
      { char: 'ଙ', name: 'Nga', accepted: ['nga', 'ng'] },
      { char: 'ଚ', name: 'Cha', accepted: ['cha', 'ch'] },
      { char: 'ଛ', name: 'Chha', accepted: ['chha', 'chh'] },
      { char: 'ଜ', name: 'Ja', accepted: ['ja', 'j'] },
      { char: 'ଝ', name: 'Jha', accepted: ['jha', 'jh'] },
      { char: 'ଟ', name: 'Ta', accepted: ['ta', 't'] },
      { char: 'ଠ', name: 'Tha', accepted: ['tha', 'th'] },
      { char: 'ଡ', name: 'Da', accepted: ['da', 'd'] },
      { char: 'ଢ', name: 'Dha', accepted: ['dha', 'dh'] },
      { char: 'ଣ', name: 'Na', accepted: ['na', 'n'] },
      { char: 'ତ', name: 'Ta', accepted: ['ta', 't'] },
      { char: 'ଥ', name: 'Tha', accepted: ['tha', 'th'] },
      { char: 'ଦ', name: 'Da', accepted: ['da', 'd'] },
      { char: 'ଧ', name: 'Dha', accepted: ['dha', 'dh'] },
      { char: 'ନ', name: 'Na', accepted: ['na', 'n'] },
      { char: 'ପ', name: 'Pa', accepted: ['pa', 'p'] },
      { char: 'ଫ', name: 'Pha', accepted: ['pha', 'ph'] },
      { char: 'ବ', name: 'Ba', accepted: ['ba', 'b'] },
      { char: 'ଭ', name: 'Bha', accepted: ['bha', 'bh'] },
      { char: 'ମ', name: 'Ma', accepted: ['ma', 'm'] },
      { char: 'ଯ', name: 'Ya', accepted: ['ya', 'y'] },
      { char: 'ର', name: 'Ra', accepted: ['ra', 'r'] },
      { char: 'ଲ', name: 'La', accepted: ['la', 'l'] },
      { char: 'ୱ', name: 'Wa', accepted: ['wa', 'w'] },
      { char: 'ଶ', name: 'Sha', accepted: ['sha', 'sh'] },
      { char: 'ଷ', name: 'Sha', accepted: ['sha', 'sh'] },
      { char: 'ସ', name: 'Sa', accepted: ['sa', 's'] },
      { char: 'ହ', name: 'Ha', accepted: ['ha', 'h'] },
    ]
  },
  {
    id: 'korean',
    title: 'Korean (Hangul)',
    description: 'The 24 basic letters of the Korean alphabet.',
    color: 'bg-indigo-600',
    items: [
      { char: 'ㄱ', name: 'G/K', accepted: ['g', 'k', 'giyeok'] },
      { char: 'ㄴ', name: 'N', accepted: ['n', 'nieun'] },
      { char: 'ㄷ', name: 'D/T', accepted: ['d', 't', 'digeut'] },
      { char: 'ㄹ', name: 'R/L', accepted: ['r', 'l', 'rieul'] },
      { char: 'ㅁ', name: 'M', accepted: ['m', 'mieum'] },
      { char: 'ㅂ', name: 'B/P', accepted: ['b', 'p', 'bieup'] },
      { char: 'ㅅ', name: 'S', accepted: ['s', 'sh', 'siot'] },
      { char: 'ㅇ', name: 'Ng', accepted: ['ng', 'ieung', 'silent'] },
      { char: 'ㅈ', name: 'J', accepted: ['j', 'jieut'] },
      { char: 'ㅊ', name: 'Ch', accepted: ['ch', 'chieut'] },
      { char: 'ㅋ', name: 'K', accepted: ['k', 'kieuk'] },
      { char: 'ㅌ', name: 'T', accepted: ['t', 'tieut'] },
      { char: 'ㅍ', name: 'P', accepted: ['p', 'pieup'] },
      { char: 'ㅎ', name: 'H', accepted: ['h', 'hieut'] },
      { char: 'ㅏ', name: 'A', accepted: ['a'] },
      { char: 'ㅑ', name: 'Ya', accepted: ['ya'] },
      { char: 'ㅓ', name: 'Eo', accepted: ['eo'] },
      { char: 'ㅕ', name: 'Yeo', accepted: ['yeo'] },
      { char: 'ㅗ', name: 'O', accepted: ['o'] },
      { char: 'ㅛ', name: 'Yo', accepted: ['yo'] },
      { char: 'ㅜ', name: 'U', accepted: ['u', 'oo'] },
      { char: 'ㅠ', name: 'Yu', accepted: ['yu'] },
      { char: 'ㅡ', name: 'Eu', accepted: ['eu'] },
      { char: 'ㅣ', name: 'I', accepted: ['i', 'ee'] },
    ]
  },
  {
    id: 'hiragana',
    title: 'Hiragana (Basic)',
    description: 'The fundamental syllabary of Japanese.',
    color: 'bg-pink-600',
    items: [
      { char: 'あ', name: 'A', accepted: ['a'] }, { char: 'い', name: 'I', accepted: ['i'] }, { char: 'う', name: 'U', accepted: ['u'] }, { char: 'え', name: 'E', accepted: ['e'] }, { char: 'お', name: 'O', accepted: ['o'] },
      { char: 'か', name: 'Ka', accepted: ['ka'] }, { char: 'き', name: 'Ki', accepted: ['ki'] }, { char: 'く', name: 'Ku', accepted: ['ku'] }, { char: 'け', name: 'Ke', accepted: ['ke'] }, { char: 'こ', name: 'Ko', accepted: ['ko'] },
      { char: 'さ', name: 'Sa', accepted: ['sa'] }, { char: 'し', name: 'Shi', accepted: ['shi', 'si'] }, { char: 'す', name: 'Su', accepted: ['su'] }, { char: 'せ', name: 'Se', accepted: ['se'] }, { char: 'そ', name: 'So', accepted: ['so'] },
      { char: 'た', name: 'Ta', accepted: ['ta'] }, { char: 'ち', name: 'Chi', accepted: ['chi', 'ti'] }, { char: 'つ', name: 'Tsu', accepted: ['tsu', 'tu'] }, { char: 'て', name: 'Te', accepted: ['te'] }, { char: 'と', name: 'To', accepted: ['to'] },
      { char: 'な', name: 'Na', accepted: ['na'] }, { char: 'に', name: 'Ni', accepted: ['ni'] }, { char: 'ぬ', name: 'Nu', accepted: ['nu'] }, { char: 'ね', name: 'Ne', accepted: ['ne'] }, { char: 'の', name: 'No', accepted: ['no'] },
      { char: 'は', name: 'Ha', accepted: ['ha'] }, { char: 'ひ', name: 'Hi', accepted: ['hi'] }, { char: 'ふ', name: 'Fu', accepted: ['fu', 'hu'] }, { char: 'へ', name: 'He', accepted: ['he'] }, { char: 'ほ', name: 'Ho', accepted: ['ho'] },
      { char: 'ま', name: 'Ma', accepted: ['ma'] }, { char: 'み', name: 'Mi', accepted: ['mi'] }, { char: 'む', name: 'Mu', accepted: ['mu'] }, { char: 'め', name: 'Me', accepted: ['me'] }, { char: 'も', name: 'Mo', accepted: ['mo'] },
      { char: 'や', name: 'Ya', accepted: ['ya'] }, { char: 'ゆ', name: 'Yu', accepted: ['yu'] }, { char: 'よ', name: 'Yo', accepted: ['yo'] },
      { char: 'ら', name: 'Ra', accepted: ['ra'] }, { char: 'り', name: 'Ri', accepted: ['ri'] }, { char: 'る', name: 'Ru', accepted: ['ru'] }, { char: 'れ', name: 'Re', accepted: ['re'] }, { char: 'ろ', name: 'Ro', accepted: ['ro'] },
      { char: 'わ', name: 'Wa', accepted: ['wa'] }, { char: 'を', name: 'Wo', accepted: ['wo', 'o'] }, { char: 'ん', name: 'N', accepted: ['n', 'nn'] },
    ]
  },
  {
    id: 'futhark',
    title: 'Elder Futhark',
    description: 'The oldest form of the runic alphabets.',
    color: 'bg-emerald-800',
    items: [
      { char: 'ᚠ', name: 'Fehu', accepted: ['fehu', 'f'] },
      { char: 'ᚢ', name: 'Uruz', accepted: ['uruz', 'u'] },
      { char: 'ᚦ', name: 'Thurisaz', accepted: ['thurisaz', 'th'] },
      { char: 'ᚨ', name: 'Ansuz', accepted: ['ansuz', 'a'] },
      { char: 'ᚱ', name: 'Raido', accepted: ['raido', 'r'] },
      { char: 'ᚲ', name: 'Kaunan', accepted: ['kaunan', 'k'] },
      { char: 'ᚷ', name: 'Gebo', accepted: ['gebo', 'g'] },
      { char: 'ᚹ', name: 'Wunjo', accepted: ['wunjo', 'w'] },
      { char: 'ᚺ', name: 'Hagalaz', accepted: ['hagalaz', 'h'] },
      { char: 'ᚾ', name: 'Naudiz', accepted: ['naudiz', 'n'] },
      { char: 'ᛁ', name: 'Isaz', accepted: ['isaz', 'i'] },
      { char: 'ᛃ', name: 'Jera', accepted: ['jera', 'j', 'y'] },
      { char: 'ᛇ', name: 'Eihwaz', accepted: ['eihwaz', 'ei', 'ï'] },
      { char: 'ᛈ', name: 'Perthro', accepted: ['perthro', 'p'] },
      { char: 'ᛉ', name: 'Algiz', accepted: ['algiz', 'z'] },
      { char: 'ᛊ', name: 'Sowilo', accepted: ['sowilo', 's'] },
      { char: 'ᛏ', name: 'Tiwaz', accepted: ['tiwaz', 't'] },
      { char: 'ᛒ', name: 'Berkanan', accepted: ['berkanan', 'b'] },
      { char: 'ᛖ', name: 'Ehwaz', accepted: ['ehwaz', 'e'] },
      { char: 'ᛗ', name: 'Mannaz', accepted: ['mannaz', 'm'] },
      { char: 'ᛚ', name: 'Laguz', accepted: ['laguz', 'l'] },
      { char: 'ᛜ', name: 'Ingwaz', accepted: ['ingwaz', 'ng'] },
      { char: 'ᛟ', name: 'Othala', accepted: ['othala', 'o'] },
      { char: 'ᛞ', name: 'Dagaz', accepted: ['dagaz', 'd'] },
    ]
  },
  {
    id: 'orkhon',
    title: 'Old Turkic (Orkhon)',
    description: 'The ancient runic script of the Göktürks.',
    color: 'bg-cyan-800',
    items: [
      { char: '𐰀', name: 'A/E', accepted: ['a', 'e'] },
      { char: '𐰃', name: 'I/Ï', accepted: ['i', 'ï'] },
      { char: '𐰆', name: 'O/U', accepted: ['o', 'u'] },
      { char: '𐰇', name: 'Ö/Ü', accepted: ['ö', 'ü', 'oe', 'ue', 'o', 'u'] },
      { char: '𐰉', name: 'B¹', accepted: ['b'] },
      { char: '𐰋', name: 'B²', accepted: ['b'] },
      { char: '𐰑', name: 'D¹', accepted: ['d'] },
      { char: '𐰓', name: 'D²', accepted: ['d'] },
      { char: '𐰍', name: 'G¹', accepted: ['g', 'gh'] },
      { char: '𐰏', name: 'G²', accepted: ['g'] },
      { char: '𐰞', name: 'L¹', accepted: ['l'] },
      { char: '𐰠', name: 'L²', accepted: ['l'] },
      { char: '𐰣', name: 'N¹', accepted: ['n'] },
      { char: '𐰤', name: 'N²', accepted: ['n'] },
      { char: '𐰮', name: 'Nch', accepted: ['nch', 'nj'] },
      { char: '𐰭', name: 'Ng', accepted: ['ng'] },
      { char: '𐰯', name: 'P', accepted: ['p'] },
      { char: '𐰺', name: 'R¹', accepted: ['r'] },
      { char: '𐰼', name: 'R²', accepted: ['r'] },
      { char: '𐰽', name: 'S¹', accepted: ['s'] },
      { char: '𐰾', name: 'S²', accepted: ['s'] },
      { char: '𐱃', name: 'T¹', accepted: ['t'] },
      { char: '𐱅', name: 'T²', accepted: ['t'] },
      { char: '𐰖', name: 'Y¹', accepted: ['y', 'j'] },
      { char: '𐰘', name: 'Y²', accepted: ['y', 'j'] },
      { char: '𐰴', name: 'Q', accepted: ['q', 'k'] },
      { char: '𐰚', name: 'K', accepted: ['k'] },
      { char: '𐰱', name: 'Ich/Chi', accepted: ['ich', 'chi', 'ch'] },
      { char: '𐰳', name: 'Oq/Qo', accepted: ['oq', 'qo', 'uk', 'ku'] },
      { char: '𐰵', name: 'Ök/Kö', accepted: ['ök', 'kö', 'uk', 'ku'] },
    ]
  },
  {
    id: 'tifinagh',
    title: 'Tifinagh (Berber)',
    description: 'The traditional script of the Amazigh people.',
    color: 'bg-yellow-600',
    items: [
      { char: 'ⴰ', name: 'Ya', accepted: ['ya', 'a'] },
      { char: 'ⴱ', name: 'Yab', accepted: ['yab', 'b'] },
      { char: 'ⴳ', name: 'Yag', accepted: ['yag', 'g'] },
      { char: 'ⴷ', name: 'Yad', accepted: ['yad', 'd'] },
      { char: 'ⴹ', name: 'Yadd', accepted: ['yadd', 'd'] },
      { char: 'ⴻ', name: 'Yey', accepted: ['yey', 'e'] },
      { char: 'ⴼ', name: 'Yaf', accepted: ['yaf', 'f'] },
      { char: 'ⴽ', name: 'Yak', accepted: ['yak', 'k'] },
      { char: 'ⵀ', name: 'Yah', accepted: ['yah', 'h'] },
      { char: 'ⵃ', name: 'Yahhm', accepted: ['yahhm', 'h'] },
      { char: 'ⵄ', name: 'Ya\'', accepted: ['ya', 'a'] },
      { char: 'ⵅ', name: 'Yakh', accepted: ['yakh', 'kh', 'x'] },
      { char: 'ⵇ', name: 'Yaq', accepted: ['yaq', 'q'] },
      { char: 'ⵉ', name: 'Yi', accepted: ['yi', 'i'] },
      { char: 'ⵊ', name: 'Yaj', accepted: ['yaj', 'j'] },
      { char: 'ⵍ', name: 'Yal', accepted: ['yal', 'l'] },
      { char: 'ⵎ', name: 'Yam', accepted: ['yam', 'm'] },
      { char: 'ⵏ', name: 'Yan', accepted: ['yan', 'n'] },
      { char: 'ⵓ', name: 'Yu', accepted: ['yu', 'u', 'w'] },
      { char: 'ⵔ', name: 'Yar', accepted: ['yar', 'r'] },
      { char: 'ⵕ', name: 'Yarr', accepted: ['yarr', 'r'] },
      { char: 'ⵖ', name: 'Yagh', accepted: ['yagh', 'gh'] },
      { char: 'ⵙ', name: 'Yas', accepted: ['yas', 's'] },
      { char: 'ⵚ', name: 'Yass', accepted: ['yass', 's'] },
      { char: 'ⵛ', name: 'Yash', accepted: ['yash', 'sh'] },
      { char: 'ⵜ', name: 'Yat', accepted: ['yat', 't'] },
      { char: 'ⵟ', name: 'Yatt', accepted: ['yatt', 't'] },
      { char: 'ⵡ', name: 'Yaw', accepted: ['yaw', 'w'] },
      { char: 'ⵢ', name: 'Yay', accepted: ['yay', 'y'] },
      { char: 'ⵣ', name: 'Yaz', accepted: ['yaz', 'z'] },
      { char: 'ⵥ', name: 'Yazz', accepted: ['yazz', 'z'] },
    ]
  },
  {
    id: 'hebrew',
    title: 'Hebrew',
    description: 'The abjad used for the Hebrew language.',
    color: 'bg-amber-700',
    items: [
      { char: 'א', name: 'Aleph', accepted: ['aleph', 'alef'] },
      { char: 'ב', name: 'Bet', accepted: ['bet', 'vet', 'b', 'v'] },
      { char: 'ג', name: 'Gimel', accepted: ['gimel', 'g'] },
      { char: 'ד', name: 'Dalet', accepted: ['dalet', 'd'] },
      { char: 'ה', name: 'He', accepted: ['he', 'hey', 'h'] },
      { char: 'ו', name: 'Vav', accepted: ['vav', 'vaw', 'v'] },
      { char: 'ז', name: 'Zayin', accepted: ['zayin', 'z'] },
      { char: 'ח', name: 'Het', accepted: ['het', 'chet', 'h', 'ch'] },
      { char: 'ט', name: 'Tet', accepted: ['tet', 't'] },
      { char: 'י', name: 'Yod', accepted: ['yod', 'yud', 'y'] },
      { char: 'כ', name: 'Kaf', accepted: ['kaf', 'khaf', 'k', 'kh'] },
      { char: 'ל', name: 'Lamed', accepted: ['lamed', 'l'] },
      { char: 'מ', name: 'Mem', accepted: ['mem', 'm'] },
      { char: 'נ', name: 'Nun', accepted: ['nun', 'n'] },
      { char: 'ס', name: 'Samekh', accepted: ['samekh', 's'] },
      { char: 'ע', name: 'Ayin', accepted: ['ayin'] },
      { char: 'פ', name: 'Pe', accepted: ['pe', 'fe', 'phe', 'p', 'f'] },
      { char: 'צ', name: 'Tsade', accepted: ['tsade', 'tzadi', 'ts', 'tz'] },
      { char: 'ק', name: 'Qof', accepted: ['qof', 'kuf', 'q', 'k'] },
      { char: 'ר', name: 'Resh', accepted: ['resh', 'r'] },
      { char: 'ש', name: 'Shin', accepted: ['shin', 'sin', 'sh', 's'] },
      { char: 'ת', name: 'Tav', accepted: ['tav', 'taf', 't'] },
    ]
  },
];
